# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acff61b6179c5b5463fcfacdcf3fbe99ad81bcd341ac42bdbe2822134bfd27f09e0a2e919ed56479432f3c50704cce6725abbf1063ec8ccd97b86780d670b414

test:
  secret_key_base: 49dc29940a56268cc453ea3a2bd84cf45df4d4111b3cf46538ea80534443980f5b23ab99bc1705398882418939f81a067bd3e1185e43583b4f7d20bd2dd481e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
